'use strict';

var crypto = require('crypto');
var env    = process.env.NODE_ENV || 'development';


// salt generation for hashing functions
var secret;

// salt is a simple value if we are using development environment
if (env === 'development') {
    secret = process.env.SECRET_KEY || 'aciksozluk';
} else if (env === 'test') {
    // use random generated bytes for testing environment
    secret = crypto.randomBytes(16).toString('hex');
} else {
    // secret key must be supplied as an environment variable for production environment
    // TODO: Need to document this
    secret = process.env.SECRET_KEY;
    if (!secret) {
        throw new Error('SECRET_KEY is not available!');
    }
}

module.exports = secret;
