language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c 'CREATE DATABASE aciksozluk_test;' -U postgres
script: gulp
env:
  - NODE_ENV=test
